import { chromium } from 'playwright';
import fs from 'node:fs/promises';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

const ROOT=process.cwd(), DATA=path.join(ROOT,'data'), DIAG=path.join(ROOT,'diagnostics');
const NOW=new Date(), RUN=NOW.toISOString(), TODAY=RUN.slice(0,10);
const SOURCE='NCEVP', LABEL='NC eVP', URL='https://evp.nc.gov/solicitations/';
const BUILD=/\b(construction|construct|renov|replace|replacement|repair|rehab|building|roof|hvac|mechanical|electrical|plumbing|water|sewer|wastewater|pump|lift station|utility|road|pav|bridge|culvert|stormwater|drainage|sidewalk|concrete|masonry|demolition|sitework|site work|grading|dredg|levee|fire alarm|generator|chiller|boiler|tower|hangar|airport|airfield|trail|retaining wall|force main|pipeline|streetscape|lighting|elevator|sprinkler|parking|garage|improvement|general contractor|cmar|cm\/gc|design.?build)\b/i;
const JUNK=/\b(software|insurance|printing|office supplies|food service|catering|vehicle purchase|medical supplies|legal services|audit services|nursing|staffing|temporary labor|janitorial|custodial|grounds maintenance|landscaping|mowing|pest control|security services|medical services|health services|consulting|professional services|engineering services|architectural services|prequalification|pre-qualification|vendor qualification|request for qualifications|rfq for design|lease|rental|equipment purchase|supplies|furniture|printing services)\b/i;
const clean=s=>String(s||'').replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim();
const norm=s=>clean(s).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const recKey=o=>`${SOURCE}|${norm(o.s)}|${norm(o.n)}|NC`;
const relevant=(project,desc)=>{const core=clean([project,desc].join(' '));return BUILD.test(core)&&!JUNK.test(core)};
const future=o=>o?.d&&new Date(o.d)>NOW;

async function readJson(file,fallback){try{return JSON.parse(await fs.readFile(file,'utf8'))}catch{return fallback}}
function parseMdy(text,defaultHour=17){const s=clean(text),m=s.match(/(\d{1,2})\/(\d{1,2})\/(20\d{2})(?:\s+(\d{1,2}):(\d{2})\s*(AM|PM))?/i);if(!m)return null;let h=+(m[4]||defaultHour),min=+(m[5]||0),ap=(m[6]||'').toUpperCase();if(ap==='PM'&&h<12)h+=12;if(ap==='AM'&&h===12)h=0;const utcHour=h+4;return new Date(Date.UTC(+m[3],+m[1]-1,+m[2],utcHour,min)).toISOString()}
function money(v){return clean(v).replace(/\$\s+/g,'$')}
function romFrom(text=''){const s=clean(text);const patterns=[/(?:engineer(?:'s)? estimate|estimated construction cost|construction estimate|project estimate|estimated project cost|estimated cost|estimated amount|budget|cost range|construction range|project range|magnitude(?: of construction)?)\s*(?:is|of|:|-)?\s*(\$\s*[\d,.]+(?:\s*(?:million|thousand|[mk]))?(?:\s*(?:to|through|-|–|and)\s*\$\s*[\d,.]+(?:\s*(?:million|thousand|[mk]))?)?)/i,/(\$\s*[\d,.]+(?:\s*(?:million|thousand|[mk]))?\s*(?:to|through|-|–)\s*\$\s*[\d,.]+(?:\s*(?:million|thousand|[mk]))?)\s*(?:estimated|construction|project|range|magnitude)/i];for(const re of patterns){const m=s.match(re);if(m)return money(m[1]).slice(0,120)}return''}
function unique(rows){const m=new Map();for(const o of rows){const k=recKey(o),prev=m.get(k);if(!prev||new Date(o.u||0)>new Date(prev.u||0))m.set(k,o)}return[...m.values()]}

function historySnapshots(){const out=[];try{const shas=execFileSync('git',['log','--format=%H','--','data/priority-current.json'],{encoding:'utf8'}).trim().split(/\s+/).filter(Boolean).slice(1,12);for(const sha of shas){try{const txt=execFileSync('git',['show',`${sha}:data/priority-current.json`],{encoding:'utf8',maxBuffer:30*1024*1024});const j=JSON.parse(txt),rows=(j.records||[]).filter(o=>o.source===SOURCE&&future(o));if(rows.length)out.push({sha,rows})}catch{}}}catch{}return out}
function bestHistory(currentRows){const snaps=historySnapshots();let best={sha:'current',rows:currentRows.filter(o=>o.source===SOURCE&&future(o))};for(const s of snaps)if(s.rows.length>best.rows.length)best=s;return best}

const gridSel='.entity-grid.entitylist';
async function gridRows(p){return p.locator(`${gridSel} .view-grid table tbody tr`).evaluateAll(trs=>trs.map(tr=>({text:(tr.innerText||'').replace(/\s+/g,' ').trim(),cells:[...tr.querySelectorAll('td')].map(x=>(x.innerText||'').replace(/\s+/g,' ').trim()),links:[...tr.querySelectorAll('a[href]')].map(a=>({text:(a.innerText||'').trim(),href:a.href}))})).filter(x=>x.cells.length))}
async function activePage(p){const v=await p.locator(`${gridSel} .view-pagination li.active a[data-page]`).first().getAttribute('data-page').catch(()=>null);return +(v||1)}
async function waitLoaded(p){await p.locator(`${gridSel} .view-loading`).waitFor({state:'hidden',timeout:15000}).catch(()=>{});await p.waitForTimeout(250)}
async function goPage(p,target){const current=await activePage(p);const link=p.locator(`${gridSel} .view-pagination li:not(.disabled) a[data-page="${target}"]`).filter({hasText:/^\s*\d+\s*$/}).first();if(!await link.count())return current;if(!await link.isEnabled().catch(()=>false))return current;await link.click({timeout:10000});await p.waitForFunction(({sel,t})=>{const a=document.querySelector(sel+' .view-pagination li.active a[data-page]');return a&&Number(a.getAttribute('data-page'))===t},{sel:gridSel,t:target},{timeout:15000});await waitLoaded(p);return activePage(p)}

async function scrape(){const browser=await chromium.launch({headless:true,args:['--disable-blink-features=AutomationControlled','--no-sandbox']});const c=await browser.newContext({ignoreHTTPSErrors:true,userAgent:'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126 Safari/537.36',viewport:{width:1440,height:1000},timezoneId:'America/New_York'});const p=await c.newPage();p.setDefaultTimeout(12000);const out=[];let visited=0,totalPages=1;try{await p.goto(URL,{waitUntil:'domcontentloaded',timeout:35000});await waitLoaded(p);const openLabel=p.getByText('Open',{exact:true}).first();if(await openLabel.count())await openLabel.click().catch(()=>{});const apply=p.getByRole('button',{name:/apply/i}).first();if(await apply.count()){await apply.click().catch(()=>{});await waitLoaded(p)}for(let guard=0;guard<65;guard++){const pageNo=await activePage(p),rr=await gridRows(p);visited++;totalPages=Math.max(totalPages,pageNo);for(const r of rr){const c=r.cells;if(c.length<5)continue;const solicitation=c[0]||'',project=c[1]||'',desc=c[2]||'',status=c[5]||'';if(status&&!/open/i.test(status))continue;if(!relevant(project,desc))continue;const d=parseMdy(c[3]);if(!d||new Date(d)<=NOW)continue;const detail=(r.links.find(x=>/details|solicit/i.test(x.href+' '+x.text))||r.links[0])?.href||URL;out.push({source:SOURCE,sourceLabel:LABEL,state:'NC',s:clean(solicitation||project).slice(0,100),n:clean(project||desc).slice(0,240),d,p:parseMdy(c[4],12)||TODAY+'T12:00:00Z',l:'North Carolina',scope:'Construction',c:'Construction',r:detail,type:'State / Local',set:'State / Local',u:RUN,x:35.5,y:-79.4,approx:true,rom:romFrom(desc+' '+r.text)})}const next=pageNo+1,arrived=await goPage(p,next);if(arrived===pageNo){totalPages=pageNo;break}totalPages=Math.max(totalPages,arrived)}try{await p.screenshot({path:path.join(DIAG,`NCEVP-repair-${Date.now()}.png`),fullPage:true})}catch{}try{await fs.writeFile(path.join(DIAG,`NCEVP-repair-${Date.now()}.html`),await p.content())}catch{}return {rows:unique(out),visited,totalPages,error:null}}catch(e){return {rows:unique(out),visited,totalPages,error:e.message}}finally{await c.close();await browser.close()}}

const priorityPath=path.join(DATA,'priority-current.json'),jsPath=path.join(DATA,'priority-current.js'),healthPath=path.join(DATA,'source-health.json'),healthJs=path.join(DATA,'source-health.js');
const current=await readJson(priorityPath,{records:[]}),currentRows=current.records||[],hist=bestHistory(currentRows),live=await scrape();
const histMap=new Map(hist.rows.map(o=>[recKey(o),o])),liveRows=live.rows.map(o=>{const old=histMap.get(recKey(o));return {...old,...o,firstSeen:old?.firstSeen||old?.p||o.p||RUN,lastSeen:RUN,change:old?'ACTIVE':'NEW',stale:false}});
const suspicious=!!live.error || (hist.rows.length>=40 && liveRows.length < Math.floor(hist.rows.length*0.65));
let repaired,status,message;if(suspicious){const merged=new Map(hist.rows.filter(future).filter(o=>relevant(o.n,o.description||'')).map(o=>[recKey(o),{...o,stale:true}]));for(const o of liveRows)merged.set(recKey(o),o);repaired=[...merged.values()];status='PARTIAL';message=`NC eVP pagination repair visited ${live.visited}/${live.totalPages} page(s) and parsed ${liveRows.length} live construction pursuit(s). Continuity guard preserved the latest healthy future snapshot (${hist.rows.length}) because the live count collapsed unexpectedly${live.error?`: ${live.error}`:''}, while reapplying construction relevance filters to preserved records.`}else{repaired=liveRows;status='OK';message=`NC eVP pagination repair visited ${live.visited}/${live.totalPages} page(s) and parsed ${liveRows.length} active construction pursuit(s).`}
repaired=unique(repaired).filter(future).filter(o=>relevant(o.n,o.description||'')).sort((a,b)=>new Date(a.d)-new Date(b.d));const other=currentRows.filter(o=>o.source!==SOURCE&&(!o.d||new Date(o.d)>NOW)),final=[...repaired,...other];current.generatedAt=RUN;current.records=final;await fs.writeFile(priorityPath,JSON.stringify(current,null,2)+'\n');await fs.writeFile(jsPath,`window.MC3_DIRECT=${JSON.stringify(final)};\n`);
const health=await readJson(healthPath,{generatedAt:RUN,total:0,sources:{}});health.sources||={};health.sources[SOURCE]={label:LABEL,status,count:repaired.length,checkedAt:RUN,message,stale:status!=='OK'};health.generatedAt=RUN;health.total=Object.values(health.sources).reduce((n,s)=>n+(Number(s.count)||0),0);await fs.writeFile(healthPath,JSON.stringify(health,null,2)+'\n');await fs.writeFile(healthJs,`window.MC3_HEALTH=${JSON.stringify(health)};\n`);console.log(JSON.stringify({status,count:repaired.length,live:liveRows.length,historical:hist.rows.length,pages:`${live.visited}/${live.totalPages}`,message},null,2));
