import { chromium } from 'playwright';
import fs from 'node:fs/promises';
import path from 'node:path';
const ROOT=process.cwd(),DATA=path.join(ROOT,'data'),NOW=new Date(),RUN=NOW.toISOString();
const MONTH={january:0,february:1,march:2,april:3,may:4,june:5,july:6,august:7,september:8,october:9,november:10,december:11};
const clean=s=>String(s||'').replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim();
function opening(text){const m=clean(text).match(/Bid Opening[\s\S]*?At\s+(\d{1,2}):(\d{2})\s*([ap])\.?m\.?[\s\S]*?on\s+(?:Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)?[,]?\s*(January|February|March|April|May|June|July|August|September|October|November|December)\s+(\d{1,2}),\s+(20\d{2})/i);if(!m)return null;let h=+m[1];if(m[3].toLowerCase()==='p'&&h<12)h+=12;if(m[3].toLowerCase()==='a'&&h===12)h=0;return new Date(Date.UTC(+m[6],MONTH[m[4].toLowerCase()],+m[5],h+5,+m[2])).toISOString()}
function loc(text){const m=clean(text).match(/([A-Za-z .'-]+),\s*([A-Za-z .'-]+) County,\s*Tennessee/i);return m?`${clean(m[1])}, ${clean(m[2])} County, TN`:'Tennessee'}
function desc(text){const m=clean(text).match(/Description:\s*(.*?)(?:Pre-Bid:|Bid Opening)/i);return clean(m?.[1]||'')}
function uniq(a){const m=new Map();for(const x of a)m.set(`${x.source}|${x.s}`,x);return[...m.values()]}
const current=JSON.parse(await fs.readFile(path.join(DATA,'priority-current.json'),'utf8'));const health=JSON.parse(await fs.readFile(path.join(DATA,'source-health.json'),'utf8'));
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});let rows=[];try{const c=await browser.newContext({ignoreHTTPSErrors:true,userAgent:'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/126 Safari/537.36',timezoneId:'America/New_York'});const p=await c.newPage();const url='https://comptroller.aem.tn.extglb.tn.gov/generalservices/stream/stream/contractors/construction-bid-list.html';await p.goto(url,{waitUntil:'domcontentloaded',timeout:35000});await p.waitForTimeout(900);const chunks=await p.evaluate(()=>[...document.querySelectorAll('button.accordion-button')].map(b=>{const sel=b.getAttribute('data-bs-target');const d=sel?document.querySelector(sel):null;return{title:(b.innerText||'').replace(/\s+/g,' ').trim(),text:(d?.innerText||'').replace(/\s+/g,' ').trim()}}));for(const x of chunks){const d=opening(x.text);if(!d||new Date(d)<=NOW)continue;const s=(x.title.match(/^([0-9/.-]+)\s*-/)||[])[1]||x.title;rows.push({source:'TNSTREAM',sourceLabel:'TN STREAM',s,n:x.title.replace(/^([0-9/.-]+)\s*-\s*/,''),type:'IFB',t:'IFB',set:'State / Local',p:RUN,d,u:RUN,state:'TN',l:loc(x.text),c:'Construction',scope:'State Capital Construction',r:url,x:35.8,y:-86.4,approx:true,description:desc(x.text),firstSeen:RUN,lastSeen:RUN,change:'ACTIVE'})}await c.close()}finally{await browser.close()}
rows=uniq(rows);const prior=current.records.filter(x=>x.source==='TNSTREAM');const priorMap=new Map(prior.map(x=>[x.s,x]));rows=rows.map(x=>{const p=priorMap.get(x.s);x.firstSeen=p?.firstSeen||p?.p||RUN;x.change=!p?'NEW':(p.d!==x.d?'CHANGED':'ACTIVE');return x});current.records=current.records.filter(x=>x.source!=='TNSTREAM').concat(rows);current.generatedAt=RUN;health.generatedAt=RUN;health.total=current.records.length;health.sources.TNSTREAM={label:'TN STREAM',status:'OK',count:rows.length,checkedAt:RUN,message:`Parsed ${rows.length} future projects from the live STREAM Construction Bid List.`,stale:false};await fs.writeFile(path.join(DATA,'priority-current.json'),JSON.stringify(current,null,2)+'\n');await fs.writeFile(path.join(DATA,'priority-current.js'),`window.MC3_DIRECT=${JSON.stringify(current.records)};\n`);await fs.writeFile(path.join(DATA,'source-health.json'),JSON.stringify(health,null,2)+'\n');await fs.writeFile(path.join(DATA,'source-health.js'),`window.MC3_HEALTH=${JSON.stringify(health)};\n`);console.log(JSON.stringify(health.sources.TNSTREAM,null,2));